### Products Index request
GET http://localhost:3000/products

### Suppliers Index request
GET http://localhost:3000/suppliers

### Products Create product
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Xbox",
  "price": "350",
  "description": "A fine alternative to the best"
}

### Create Suppliers
POST http://localhost:3000/suppliers
content-type: application/json

{
  "name": "Sega Corporation",
  "email": "support@sega.com",
  "phone_number": "1-800-555-5394"
}

### Products Show request
GET http://localhost:3000/products/2

### Suppliers Show request
GET http://localhost:3000/suppliers/2

### Products Update request
PATCH http://localhost:3000/products/8
content-type: application/json

{
  "supplier_id": 4,
  "description": "A great classic"
}

### Suppliers Update request
PATCH http://localhost:3000/suppliers/2
content-type: application/json

{
  "name": "Sony Corporation of North America"
}

### Products Delete request
DELETE http://localhost:3000/products/12

### Suppliers Delete request
DELETE http://localhost:3000/suppliers/5