@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMyNDgzNjF9.G-zP1snMG8Cc106OddZu4b_pWWerOHZWGRsGv_wzSds


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}



### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}


### Carted Products Index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}

### Carted Products Create
POST http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "product_id": 2,
  "quantity": 3
}

### Carted Products Destroy
DELETE http://localhost:3000/carted_products/1
Authorization: Bearer {{jwt}}


### Orders Index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}
### Orders Create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "product_id": 2,
  "quantity": 3
}

### Orders Show
GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}




### Products Index
GET http://localhost:3000/products

### Products Create
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Xbox",
  "price": "350",
  "description": "A fine alternative to the best"
}

### Products Show request
GET http://localhost:3000/products/2

### Products Update request
PATCH http://localhost:3000/products/8
content-type: application/json

{
  "supplier_id": 4
}

### Products Delete request
DELETE http://localhost:3000/products/12




### Suppliers Index
GET http://localhost:3000/suppliers

### Suppliers Create
POST http://localhost:3000/suppliers
content-type: application/json

{
  "name": "Nintendo",
  "email": "support@nintendo.com",
  "phone_number": "1-800-123-4567"
}
### Suppliers Show request
GET http://localhost:3000/suppliers/2
Authorization: Bearer {{jwt}}

### Suppliers Update request
PATCH http://localhost:3000/suppliers/2
content-type: application/json

{
  "name": "Sony Corporation of North America"
}

### Suppliers Delete request
DELETE http://localhost:3000/suppliers/5