### Index request
GET http://localhost:3000/products

### Create product
POST http://localhost:3000/products
content-type: application/json

{
  "name": "Xbox",
  "price": "350",
  "description": "A fine alternative"
}

### Show request
GET http://localhost:3000/products/2